// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9K_k8PiKtEYnfdAIgvZ4gHaZciGgwGJc',
    appId: '1:536152083464:web:69975713cd052d1e0855bd',
    messagingSenderId: '536152083464',
    projectId: 'bee-mood-tracker-2',
    authDomain: 'bee-mood-tracker-2.firebaseapp.com',
    storageBucket: 'bee-mood-tracker-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjZrYiFoKT9Fv9fcz2X82ZTsHiCjjOwk0',
    appId: '1:536152083464:android:86322bc5cbca5df80855bd',
    messagingSenderId: '536152083464',
    projectId: 'bee-mood-tracker-2',
    storageBucket: 'bee-mood-tracker-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAev1WHpqmsX4IYoYinmDxPkmqBXtb4Wss',
    appId: '1:536152083464:ios:0eea9d71edfc57450855bd',
    messagingSenderId: '536152083464',
    projectId: 'bee-mood-tracker-2',
    storageBucket: 'bee-mood-tracker-2.appspot.com',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAev1WHpqmsX4IYoYinmDxPkmqBXtb4Wss',
    appId: '1:536152083464:ios:2e897ee75f00e17d0855bd',
    messagingSenderId: '536152083464',
    projectId: 'bee-mood-tracker-2',
    storageBucket: 'bee-mood-tracker-2.appspot.com',
    iosBundleId: 'com.example.moodTracker.RunnerTests',
  );
}
